EVRL_PATH="/home/azureuser/cloudfiles/code/SRC/RL/verl/"
export CUDA_VISIBLE_DEVICES="0"
export LD_LIBRARY_PATH=/anaconda/envs/azureml_py38/lib:$LD_LIBRARY_PATH
export CONDA_PYTHON_EXE="/anaconda/envs/azureml_py38/bin/python"
export HF_HOME="~/cloudfiles/code/Cache/HF/"
export DISABLE_MLFLOW_INTEGRATION='TRUE'
export TF_ENABLE_ONEDNN_OPTS="0"
export PYTHONPATH=$EVRL_PATH:$PYTHONPATH

export HYDRA_FULL_ERROR=1
export TENSORBOARD_DIR="tensorboard_log"
export BT_VRF_PATH="FreedomIntelligence/medical_o1_verifier_3B"
export BT_VRF_DEV="cuda:0"
export BT_VRF_MAXLEN=10240


PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo   \
    data.train_files=$EVRL_PATH/BT/data/gsm8k/train.parquet \
    data.val_files=$EVRL_PATH/BT/data/gsm8k/test.parquet \
    data.train_batch_size=256 \
    data.val_batch_size=1312 \
    data.max_prompt_length=512 \
    data.max_response_length=256 \
    actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct \
    +actor_rollout_ref.actor.fsdp_config.model_dtype=bfloat16 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=4 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=8 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.4 \
    actor_rollout_ref.rollout.enforce_eager=False \
    actor_rollout_ref.rollout.free_cache_engine=False \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=4 \
    +actor_rollout_ref.ref.fsdp_config.model_dtype=bfloat16 \
    critic.optim.lr=1e-5 \
    critic.model.path=Qwen/Qwen2.5-0.5B-Instruct \
    +critic.model.fsdp_config.model_dtype=bfloat16 \
    critic.ppo_micro_batch_size_per_gpu=4 \
    reward_model.enable=True \
    reward_model.model.path=FreedomIntelligence/medical_o1_verifier_3B \
    reward_model.micro_batch_size_per_gpu=4 \
    reward_model.reward_manager=batch \
    custom_reward_function.path=/home/azureuser/cloudfiles/code/SRC/RL/verl/BT/cuz/rwdfunc/gsm8kBatch.py \
    custom_reward_function.name=compute_score \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=['console','tensorboard'] \
    trainer.project_name='tstgsm8k' \
    trainer.experiment_name='qw05' \
    trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=3 \
    trainer.resume_mode=resume_path \
    trainer.resume_from_path=/home/azureuser/cloudfiles/code/SRC/RL/verl/BT/script/checkpoints/tstgsm8k/qw05/global_step_3 \
    trainer.test_freq=3 \
    trainer.total_epochs=15 2>&1 | tee verl_demo.log

#